### ISSUE TITLE
Conflicting with "Automatic Backlinks to note" plugin

### ISSUE THREAD

**Issue by 235** [personalizedrefrigerator/joplin-plugin-revealjs-slides#2] opened 2024-01-17 17:16 UTC
Hi, amazing work! Heads-up, I found though it appears to conflict with "[Automatic Backlinks to note](https://github.com/personalizedrefrigerator/joplin-plugin-revealjs-slides/issues/new?assignees=&labels=enhancement&projects=&template=feature_request.md&title=#)" plugin. When it's turned on, I'm either getting a wrong note to be rendered (likely linked), or just empty note rendered. I suspect that's because the backlinks plugin is dynamically trying to change all the views, but not sure how to triage this issue. Would appreciate a suggestion!

**Comment by personalizedrefrigerator** [comment] 2024-01-18 23:08
Thank you for reporting this!

The RevealJS Slides plugin gets the rendered content of the current note with a `markdown-it` plugin that wraps `markdownIt.render`. Looking at [the Automatic backlinks plugin's content script](https://github.com/ambrt/joplin-plugin-referencing-notes/blob/master/src/notesReferences.js) I suspect that this issue is caused by the Automatic Backlinks plugin's lack of a `</style>` in its `<style>` tag.

As such, this [pull request on the repository](https://github.com/ambrt/joplin-plugin-referencing-notes/pull/15) may also fix this issue.

**Comment by 235** [comment] 2024-02-10 18:34
Thank you for looking into this! Waiting for that patch to land to get backlinks back.

**Comment by personalizedrefrigerator** [comment] 2024-03-26 19:27
This may be fixed in version 0.8.2 — the Reveal.js plugin now gets rendered HTML from the note viewer in a slightly different way.

**Comment by personalizedrefrigerator** [comment] 2024-06-12 01:28
I'm closing this, as I think this is fixed.

If this is still an issue, please let me know and I can re-open this.

**Closed by personalizedrefrigerator** 2024-06-12 01:28 UTC
Labels: bug
